gha

diff --git a/.github/workflows/without-environments.yml b/.github/workflows/without-environments.yml
--- a/.github/workflows/without-environments.yml
+++ b/.github/workflows/without-environments.yml
@@ -87,6 +87,10 @@ jobs:
     name: 1. Plan on INT   
     runs-on: ubuntu-latest
     needs: [ _0_build ]
+    env:
+      AWS_DEFAULT_REGION: eu-west-1
+      AWS_ACCESS_KEY_ID: ${{ secrets.INT_AWS_ACCESS_KEY_ID }}
+      AWS_SECRET_ACCESS_KEY: ${{ secrets.INT_AWS_SECRET_ACCESS_KEY }}
     steps:
       - name: Get Environment Status
         id: ssm-int-planned
@@ -94,12 +98,33 @@ jobs:
         with:
           action: "get"
           param-name: "/int/planned"
-          #param-value: ${{ github.event.inputs.param-value }} SHA
-        env:
-          AWS_DEFAULT_REGION: eu-west-1
-          AWS_ACCESS_KEY_ID: ${{ secrets.INT_AWS_ACCESS_KEY_ID }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.INT_AWS_SECRET_ACCESS_KEY }}
 
-      - name: Get the param output
-        run: echo "The param value ${{ steps.ssm-int-planned.outputs.param-value }}"
+      - name: Check Deployment Status
+        # Fail if plan already run on int
+        if: steps.ssm-int-planned.outputs.param-value == github.sha && github.event.inputs.action == '1-plan-int'
+        run: |
+          echo "::error::Plan already run on INT"
+          exit 1
+
+      - name: Check Deployment Order
+        # Fail if user does not follow deployment order
+        if: steps.ssm-int-planned.outputs.param-value != github.sha && github.event.inputs.action != '1-plan-int'
+        run: |
+          echo "::error::Please run '1-plan-int' before '${{ github.event.inputs.action }}'"
+          exit 1
+
+      - name: Plan on INT
+        id: action
+        # Run plan on int if changes have been made and requested by user
+        if: steps.ssm-int-planned.outputs.param-value != github.sha && github.event.inputs.action == '1-plan-int'
+        shell: bash
+        run: |
+          echo "Planning on INT"
+          echo "::set-output name=action_run::$(echo 'true')"
   
+      - name: Update Environment Status
+        uses: ben-poole/param-store-javascript-action@v6
+        with:
+          action: "put"
+          param-name: "/int/planned"
+          param-value: ${{ github.sha }}
