gha

diff --git a/.github/workflows/without-environments.yml b/.github/workflows/without-environments.yml
--- a/.github/workflows/without-environments.yml
+++ b/.github/workflows/without-environments.yml
@@ -128,3 +128,49 @@ jobs:
           action: "put"
           param-name: "/int/planned"
           param-value: ${{ github.sha }}
+
+  _2_int_deploy:
+    name: 2. Deploy on INT   
+    runs-on: ubuntu-latest
+    needs: [ _0_build, _1_int_plan ]
+    env:
+      AWS_DEFAULT_REGION: eu-west-1
+      AWS_ACCESS_KEY_ID: ${{ secrets.INT_AWS_ACCESS_KEY_ID }}
+      AWS_SECRET_ACCESS_KEY: ${{ secrets.INT_AWS_SECRET_ACCESS_KEY }}
+    steps:
+      - name: Get Environment Status
+        id: ssm-int-deployed
+        uses: ben-poole/param-store-javascript-action@v6
+        with:
+          action: "get"
+          param-name: "/int/deployed"
+
+      - name: Check Deployment Status
+        # Fail if plan already run on int
+        if: steps.ssm-int-deployed.outputs.param-value == github.sha && github.event.inputs.action == '2-deploy-int'
+        run: |
+          echo "::error::Plan already run on INT"
+          exit 1
+
+      - name: Check Deployment Order
+        # Fail if user does not follow deployment order
+        if: steps.ssm-int-deployed.outputs.param-value != github.sha && github.event.inputs.action != '2-deploy-int'
+        run: |
+          echo "::error::Please run '2-deploy-int' before '${{ github.event.inputs.action }}'"
+          exit 1
+
+      - name: Deploy on INT
+        id: action
+        # Run plan on int if changes have been made and requested by user
+        if: steps.ssm-int-deployed.outputs.param-value != github.sha && github.event.inputs.action == '2-deploy-int'
+        shell: bash
+        run: |
+          echo "Deploying on INT"
+          echo "::set-output name=action_run::$(echo 'true')"
+  
+      - name: Update Environment Status
+        uses: ben-poole/param-store-javascript-action@v6
+        with:
+          action: "put"
+          param-name: "/int/deployed"
+          param-value: ${{ github.sha }}
